version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: subscription-tracker-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 80554556
      POSTGRES_DB: subscription_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d subscription_tracker"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build: ./back-end
    container_name: subscription-tracker-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: 80554556
      DB_NAME: subscription_tracker
      DB_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # Frontend application
  frontend:
    build: ./front-end
    container_name: subscription-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge